### ISSUE TITLE
Correction for Azure Key Vault is used to store secrets for Azure Active Directory (Azure AD) user accounts.

### ISSUE THREAD

**Issue by EChDatAnyl** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#10]
Falsely placed as Server applications. This is corrected as No Change.

See https://learn.microsoft.com/en-us/training/modules/azure-key-vault/3-access

**Comment by danieldanielecki** [comment]
Hey @EChDatAnyl, thanks for opening the issue, but the answer marked `Server applications.` is correct.

Please read one of these answers about admin accounts. Why would `Azure Key Vault` store normal user accounts while not admin accounts? It doesn't make sense; that's why `Azure Active Directory (Azure AD) administrative accounts.` and `No change is needed.` must be dropped. `Personally Identifiable Information (PII).` doesn't make sense, so `Server applications.` is the correct answer.

Thank you:)
