### ISSUE TITLE
Correction on question 52

### ISSUE THREAD

**Issue by Bernasss12** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#12]
https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#is-it-possible-to-merge-subscriptions-into-a-single-subscription

I believe the correct answer should be "No", I haven't seen it written explicitly in any Microsoft documentation but every other source has said it is not allowed by default so the correct answer should be no.

Sources:
https://www.examtopics.com/discussions/microsoft/view/45977-exam-az-900-topic-1-question-103-discussion/
![image](https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers/assets/6233500/1d38da36-7a17-438e-a945-6811688e2de8)
(Featured snipped that appears to be behind a paywall on LinkedIn)

Hope this helped, if anyone has any counter perspective feel free to call me out

**Comment by danieldanielecki** [comment]
That's correct; even very similar question https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#two-azure-subscriptions-can-be-merged-into-a-single-subscription has the correct answer.

Fixed in https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers/commit/f57ec275710f6674b3fb2121b9a7b341e04e9ff0, thank you @Bernasss12 for contributing!
